@startuml


    !startsub persons

        object "<u>Josiah:Person</u>" as Josiah #ffffff {
           personName = {
           \t firstNames = "Josiah"@en ^^ Multilingual_String
           \t familyNames = "Carberry"@en ^^ Multilingual_String
           } ^^ PersonName
           description = "Josiah Stinkney Carberry is a fictional professor,
           \t created as a joke in 1929. He is said to still teach at Brown University,
           \t and to be known for his work in "psychoceramics", the supposed study of
           \t "cracked pots". See his Wikipedia entry for more details."@en ^^ Multilingual_String
           keywords = ["psychoceramics"@en "ionian philology"@en] List<Multilingual_String>
           orcid_id = "https://orcid.org/0000-0002-1825-0097" ^^ ORCID_iD
           scopus_author_id = "7007156898" ^^ SCOPUS_Author_ID
           websiteURL = "http://library.brown.edu/about/hay/carberry.php"
           otherIDs = [
           \t\t\t {
           \t\t\t\t label = "Wikipedia Entry"@en ^^ Multilingual_String
           \t\t\t\t value = "http://en.wikipedia.org/wiki/Josiah_Carberry" ^^ String
           \t\t\t}
           \t\t] ^^ List<ID>
        }

    !endsub

    !startsub expertise

        object "<u>Experimenting in Chemistry:ExpertiseAndSkills</u>" as ExperimentingInChemistry #ffffff {
            description = "Expertise which enables conducting an experiment
            \t and reseach in the field of chemistry"@en ^^ Multilingual_String
        }

        object "<u>Experimenting in Chemistry Possession:ExpertiseAndSkillsPossession</u>" as ExperimentingInChemistryPossession #ffffff {

        }

        ExperimentingInChemistryPossession o--> Josiah : owner >

        ExperimentingInChemistryPossession o--> ExperimentingInChemistry : skill or expertise >

    !endsub

    !startsub institutions

        object "<u>Brown University:Organisation_Unit</u>" as BrownUniversity #ffffff {
            name = "Brown University"@en ^^ Multilingual_String
            rorId = "https://ror.org/05gq02987" ^^ ROR_ID_Type
            websiteURL = "https://www.brown.edu/" ^^ URI
            address = {
            \tcity = "Providence"@en ^^ Multilingual_String
            \tstateOrProvince = "Rhode Island"@en ^^ Multilingual_String
            \tcountry = "USA"@en ^^ Multilingual_String
            } ^^ Postal_Address
        }

        object "<u>NIH:Organisation_Unit</u>" as NIH #ffffff {
            name = "National Institutes of Health"@en ^^ Multilingual_String
            rorId = "https://ror.org/01cwqze88" ^^ ROR_ID_Type
            websiteURL = "https://www.nih.gov/" ^^ URI
            address = {
            \tstateOrProvince = "Maryland"@en ^^ Multilingual_String
            \tcountry = "USA"@en ^^ Multilingual_String
            } ^^ Postal_Address
        }

    !endsub

    !startsub employments

        object "<u>Josiah Brown University:Employment</u>" as JosiahBrownUniversity #ffffff {
            dateRange = {
            \t startDate = "1929-02-29" ^^ Date
            \t startDateInclusive = "true" ^^ Boolean
            } ^^ Date_Range
            positionTitle = {
            \t title = "Professor"@en ^^ Date
            } ^^ Position_Title
        }

        JosiahBrownUniversity o--> Josiah : actor >

        JosiahBrownUniversity o--> BrownUniversity : involved in >

    !endsub

    !startsub articles

        object "<u>Restricted Access: Restricted Access COAR v.1.0 Accessibility Specification</u>" as RestrictedAccess #00ff00

        object "<u>IEEE_TPS : Journal</u>" as IEEE_TPS #00ff00 {
            title = "IEEE Transactions on Plasma Science"@en ^^ Multilingual_String
            issn = "1939-9375" ^^ ISSN
        }

        object "<u>10.1109/TPS.1987.4316723 : Journal Article</u>" as Article101109 #00ff00 {
            DOI = "10.1109/TPS.1987.4316723" ^^ DOI_Type
            title = "Bulk and surface plasmons in
            \t artificially structured materials"@en ^^ Multilingual_String
            publicationDate = 1987 ^^ Date
            startPage = "394"
            endPage = "410"
            volume = "15"
            number = "4"
        }

        Article101109 o--> IEEE_TPS : source >

        Article101109 o--> RestrictedAccess : accessRights >

    !endsub

    !startsub authorships

         object "<u>Josiah Article101109:Authorship</u>" as JosiahArticle101109 #ffffff {
             correspondingAuthor = "false" ^^ Boolean
         }

         object "<u>Affiliation Josiah : Affiliation_Statement</u>" as AffiliationJosiah #ffffff {
             displayAffiliation = "Brown University of Providence, Providence, RI, USA" ^^ String
             displayPersonName = "Josiah S. Carberry" ^^ String
         }

         JosiahArticle101109 o--> AffiliationJosiah : affiliation >

         JosiahBrownUniversity o--> AffiliationJosiah : is the foundation for >

         JosiahArticle101109 o--> Josiah : actor >

         JosiahArticle101109 o--> Article101109 : document >

         object "<u>John Article101109:Authorship</u>" as JohnArticle101109 #ffffff {
              correspondingAuthor = "true" ^^ Boolean
         }

         object "<u>Affiliation John Article101109 : Affiliation_Statement</u>" as AffiliationJohnArticle101109 #ffffff {
              displayAffiliation = "Brown University of Providence, Providence, RI, USA" ^^ String
              displayPersonName = "John J. Quinn" ^^ String
         }

         JohnArticle101109 o--> AffiliationJohnArticle101109 : affiliation >

         JohnArticle101109 o--> Article101109 : document >


    !endsub

    !startsub project

        object "<u>INSP:Project</u>" as INSP #ffffff {
             name = "Investigation of novel surface plasmons"@en ^^ Multilingual_String
             acronym = "INSP" ^^ String
             dateRange = {
             \t startDate = "1985-02-29" ^^ Date
             \t startDateInclusive = "true" ^^ Boolean
             \t endDate = "1989-02-29" ^^ Date
             \t endDateInclusive = "true" ^^ Boolean
             } ^^ Date_Range
        }

        object "<u>INSP WP1:Project</u>" as INSP_WP1 #ffffff {
             name = "Artificially structured materials"@en ^^ Multilingual_String
             acronym = "WP1" ^^ String
        }

        object "<u>INSP WP1 T1:Project</u>" as INSP_WP1_T1 #ffffff {
             name = "Bulk and surface collective charge density"@en ^^ Multilingual_String
             acronym = "WP1_T1" ^^ String
        }

        INSP_WP1_T1 o--> INSP_WP1 : part of >

        INSP_WP1 o--> INSP : part of >

        object "<u>NIH 1049:Funding</u>" as NIH_1049 #ffffff {
             grantID = 1049 ^^ Grant_ID
             budget = {
             \t amount = 1000000 ^^ Decimal
             \t currencyCode = "USD" ^^ ISO_4217_Alpha_Code
             } ^^ Monetary_Ammount
        }

        INSP o--> NIH_1049 : funding source >

        NIH_1049 o--> NIH : agency >

        object "<u>NIH 1049 WP1:Funding</u>" as NIH_1049_WP1 #ffffff {
             budget = {
             \t amount = 200000 ^^ Decimal
             \t currencyCode = "USD" ^^ ISO_4217_Alpha_Code
             } ^^ Monetary_Ammount
        }

        INSP_WP1 o--> NIH_1049_WP1 : funding source >

        object "<u>NIH 1049 WP1 Task1:Funding</u>" as NIH_1049_WP1_Task1 #ffffff {
             budget = {
             \t amount = 50000 ^^ Decimal
             \t currencyCode = "USD" ^^ ISO_4217_Alpha_Code
             } ^^ Monetary_Ammount
        }

        INSP_WP1_T1 o--> NIH_1049_WP1_Task1 : funding source >

        object "<u>NIH 1049 WP1 Task1 Josiah:Funding</u>" as NIH_1049_WP1_Task1_Josiah #ffffff {
             budget = {
             \t amount = 5000 ^^ Decimal
             \t currencyCode = "USD" ^^ ISO_4217_Alpha_Code
             } ^^ Monetary_Ammount
        }

        NIH_1049_WP1_Task1_Josiah o--> NIH_1049_WP1_Task1 : part of >

        object "<u>NIH 1049 Josiah:Funding</u>" as NIH_1049_Josiah #ffffff {
             budget = {
             \t amount = 25000 ^^ Decimal
             \t currencyCode = "USD" ^^ ISO_4217_Alpha_Code
             } ^^ Monetary_Ammount
        }

        NIH_1049_Josiah o--> NIH_1049 : part of >

        NIH_1049_WP1_Task1 o--> NIH_1049_WP1 : part of >

        NIH_1049_WP1 o--> NIH_1049 : part of >

        object "<u>NIH 1049 dissemination:Funding</u>" as NIH_1049_dissemination #ffffff {
             budget = {
             \t amount = 40000 ^^ Decimal
             \t currencyCode = "USD" ^^ ISO_4217_Alpha_Code
             } ^^ Monetary_Ammount
        }

        INSP o--> NIH_1049_dissemination : funding source >

        NIH_1049_dissemination o--> NIH_1049 : part of >

        object "<u>NIH 1049 dissemination Article101109:Funding</u>" as NIH_1049_dissemination_Article101109 #ffffff {
             budget = {
             \t amount = 1000 ^^ Decimal
             \t currencyCode = "USD" ^^ ISO_4217_Alpha_Code
             } ^^ Monetary_Ammount
        }

        NIH_1049_dissemination_Article101109 o--> NIH_1049_dissemination : part of >

        object "<u>Brown University dissemination Article101109:Funding</u>" as Brown_University_dissemination_Article101109 #ffffff {
             budget = {
             \t amount = 500 ^^ Decimal
             \t currencyCode = "USD" ^^ ISO_4217_Alpha_Code
             } ^^ Monetary_Ammount
        }

        Brown_University_dissemination_Article101109 o--> BrownUniversity : agency >

    !endsub

    !startsub contributionStatementToArticle

        object "<u>Josiah Contribution Statement to Article:CRediTContributionStatement</u>" as JosiahContributionStatementToArticle #00ff00 {
             roleType = Writing - original draft ^^ CRediT_Role_Type
             degreeOfContribution = Lead ^^ CRediT_Degree_of_Contribution
        }

        object "<u>Josiah Resource Usage Statement Article:ResourceUsageStatement</u>" as JosiahResourceUsageStatementArticle #ffffff {
            statement = "This work was supported by the NIH [grant number 1049]."@en ^^ Multilingual_String
        }

        JosiahContributionStatementToArticle o--> JosiahResourceUsageStatementArticle : resource usage statement >

        JosiahResourceUsageStatementArticle o--> NIH_1049 : funding >

        JosiahArticle101109 o--> JosiahContributionStatementToArticle : contribution statement >

    !endsub

    !startsub contributionToProject

        object "<u>Josiah Contribution to Project:ContributionToProject</u>" as JosiahContributionToProject #ffffff {
             dateRange = {
               \t startDate = "1985-02-29" ^^ Date
               \t startDateInclusive = "true" ^^ Boolean
               \t endDate = "1989-02-29" ^^ Date
               \t endDateInclusive = "true" ^^ Boolean
             } ^^ Date_Range
        }

        JosiahContributionToProject o--> AffiliationJosiah : affiliation statement >

        JosiahContributionToProject o--> Josiah : of >

        JosiahContributionToProject o--> INSP : to >

        object "<u>Josiah Contribution to WP:ContributionToProject</u>" as JosiahContributionToWP #ffffff {
             dateRange = {
               \t startDate = "1986-02-29" ^^ Date
               \t startDateInclusive = "true" ^^ Boolean
               \t endDate = "1988-02-29" ^^ Date
               \t endDateInclusive = "true" ^^ Boolean
             } ^^ Date_Range
        }

        JosiahContributionToWP o--> AffiliationJosiah : affiliation statement >

        JosiahContributionToWP o--> Josiah : of >

        JosiahContributionToWP o--> INSP_WP1 : to >

        object "<u>Josiah Contribution to WP Task:ContributionToProject</u>" as JosiahContributionToWPTask #ffffff {
             dateRange = {
               \t startDate = "1987-02-29" ^^ Date
               \t startDateInclusive = "true" ^^ Boolean
               \t endDate = "1988-02-29" ^^ Date
               \t endDateInclusive = "true" ^^ Boolean
             } ^^ Date_Range
        }

        JosiahContributionToWPTask o--> AffiliationJosiah : affiliation statement >

        JosiahContributionToWPTask o--> Josiah : of >

        JosiahContributionToWPTask o--> INSP_WP1_T1 : to >

        JosiahContributionToWPTask o--> Article101109 : evindeced by >

    !endsub

    !startsub contributionToDocument


        object "<u>Brown University Contribution to Article101109:ContributionToDocument</u>" as BrownUniversityContributionToArticle101109 #ffffff {

        }

        BrownUniversityContributionToArticle101109 o--> BrownUniversity : of >

        BrownUniversityContributionToArticle101109 o--> Article101109 : to >


    !endsub

    !startsub contributionStatementToProject

        object "<u>JosiahContributionStatementToProject:ContributionStatement</u>" as JosiahContributionStatementToProject #ffffff {
             statement = "Participate in the project as a researcher"@en ^^ Multilingual_String
        }

        object "<u>JosiahContributionStatementToWP1:ContributionStatement</u>" as JosiahContributionStatementToWP1 #ffffff {
             statement = "Lead the WP1"@en ^^ Multilingual_String
        }

        object "<u>JosiahContributionStatementToWP1Task1:TimeContributionStatement</u>" as JosiahContributionStatementToWP1Task1 #ffffff {
             statement = "Participate in the Task 1 of the WP1 by providing his
             \t expertise"@en ^^ Multilingual_String
             time = "65 hours" ^^ Time_Ammount
        }

        object "<u>JosiahResourceUsageStatementProject:FundingUsageStatement</u>" as JosiahResourceUsageStatementProject #ffffff {
             statement = "Researcher time paid from the NIH [grant number 1049]."@en ^^ Multilingual_String
        }

        JosiahContributionStatementToProject o--> JosiahResourceUsageStatementProject : resource usage statement >

        JosiahResourceUsageStatementProject o--> NIH_1049_Josiah : funding >

        object "<u>JosiahResourceUsageStatementWP:ResourceUsageStatement</u>" as JosiahResourceUsageStatementWP #ffffff {
             statement = "Researcher time paid from the NIH [grant number 1049]. Total salary used for researcher for this WP is 15,000 USD."@en ^^ Multilingual_String
        }

        JosiahContributionStatementToWP1 o--> JosiahResourceUsageStatementWP : resource usage statement >

        JosiahResourceUsageStatementWP o--> NIH_1049_WP1 : funding >

        object "<u>JosiahResourceUsageStatementTask:FundingUsageStatement</u>" as JosiahResourceUsageStatementTask #ffffff {
             statement = "Researcher time paid from the NIH [grant number 1049]. "@en ^^ Multilingual_String
        }

        JosiahContributionStatementToWP1Task1 o--> JosiahResourceUsageStatementTask : resource usage statement >

        JosiahResourceUsageStatementTask o--> NIH_1049_WP1_Task1_Josiah : funding >

        JosiahContributionStatementToWP1Task1 o--> ExperimentingInChemistryPossession : provides >

        JosiahContributionToProject o--> JosiahContributionStatementToProject : contribution statement >

        JosiahContributionToWP o--> JosiahContributionStatementToWP1 : contribution statement >

        JosiahContributionToWPTask o--> JosiahContributionStatementToWP1Task1 : contribution statement >

    !endsub

    !startsub contributionStatementToDocument

        object "<u>BrownUniversityContributionStatementToArticle:ContributionStatement</u>" as BrownUniversityContributionStatementToArticle #ffffff {
             statement = "Paying 1,500 USD for APC and open-access for
             \t journal article"@en ^^ Multilingual_String
        }

        object "<u>BrownUniversityResourceUsageStatementTaskArticle:FundingUsageStatement</u>" as BrownUniversityResourceUsageStatementTaskArticle #ffffff {
             statement = "Paying of part of APC and open-access to article covered by the NIH [grant number 1049]. "@en ^^ Multilingual_String
        }

        BrownUniversityContributionStatementToArticle o--> BrownUniversityResourceUsageStatementTaskArticle : resource usage statement >

        BrownUniversityResourceUsageStatementTaskArticle o--> NIH_1049_dissemination_Article101109 : funding >

        BrownUniversityContributionStatementToArticle o--> Brown_University_dissemination_Article101109 : provides >

        BrownUniversityContributionToArticle101109 o--> BrownUniversityContributionStatementToArticle : contribution statement >

    !endsub

@enduml