@startuml


    !startsub persons

        object "<u>Josiah:Person</u>" as Josiah #ffffff {
               personName = {
               \t firstNames = "Josiah"@en ^^ Multilingual_String
               \t familyNames = "Carberry"@en ^^ Multilingual_String
               } ^^ PersonName
               description = "Josiah Stinkney Carberry is a fictional professor,
               \t created as a joke in 1929. He is said to still teach at Brown University,
               \t and to be known for his work in "psychoceramics", the supposed study of
               \t "cracked pots". See his Wikipedia entry for more details."@en ^^ Multilingual_String
               keywords = ["psychoceramics"@en "ionian philology"@en] List<Multilingual_String>
               orcid_id = "https://orcid.org/0000-0002-1825-0097" ^^ ORCID_iD
               scopus_author_id = "7007156898" ^^ SCOPUS_Author_ID
               websiteURL = "http://library.brown.edu/about/hay/carberry.php"
               otherIDs = [
               \t\t\t {
               \t\t\t\t label = "Wikipedia Entry"@en ^^ Multilingual_String
               \t\t\t\t value = "http://en.wikipedia.org/wiki/Josiah_Carberry" ^^ String
               \t\t\t}
               \t\t] ^^ List<ID>
            }

    !endsub

    !startsub institutions

        object "<u>Wesleyan University:Organisation_Unit</u>" as WesleyeanUniversity #ffffff {
                name = "Wesleyan University"@en ^^ Multilingual_String
                rorId = "https://ror.org/05h7xva58" ^^ ROR_ID
                websiteURL = "https://www.wesleyan.edu/" ^^ URI
                address = {
                \tcity = "Midletown"@en ^^ Multilingual_String
                \tstateOrProvince = "Connecticut"@en ^^ Multilingual_String
                \tcountry = "USA"@en ^^ Multilingual_String
                } ^^ Postal_Address
            }

        object "<u>Brown University:Organisation_Unit</u>" as BrownUniversity #ffffff {
                name = "Brown University"@en ^^ Multilingual_String
                rorId = "https://ror.org/05gq02987" ^^ ROR_ID_Type
                websiteURL = "https://www.brown.edu/" ^^ URI
                address = {
                \tcity = "Providence"@en ^^ Multilingual_String
                \tstateOrProvince = "Rhode Island"@en ^^ Multilingual_String
                \tcountry = "USA"@en ^^ Multilingual_String
                } ^^ Postal_Address
            }

    !endsub

    !startsub employments

        object "<u>Josiah Wesleyan University:Employment</u>" as JosiahWesleyeanUniversity #ffffff {
                dateRange = {
                \t startDate = "1930-02-29" ^^ Date
                \t startDateInclusive = "true" ^^ Boolean
                } ^^ Date_Range
                positionTitle = {
                \t title = "Professor"@en ^^ Multilingual_String
                } ^^ Position_Title
            }

        object "<u>Josiah Brown University:Employment</u>" as JosiahBrownUniversity #ffffff {
                dateRange = {
                \t startDate = "1929-02-29" ^^ Date
                \t startDateInclusive = "true" ^^ Boolean
                } ^^ Date_Range
                positionTitle = {
                \t title = "Professor"@en ^^ Date
                } ^^ Position_Title
            }

        JosiahWesleyeanUniversity o--> Josiah : actor >

        JosiahBrownUniversity o--> Josiah : actor >

        JosiahWesleyeanUniversity o--> WesleyeanUniversity : involved in >

        JosiahBrownUniversity o--> BrownUniversity : involved in >

    !endsub

    !startsub articles

        object "<u>Restricted Access: Restricted Access COAR v.1.0 Accessibility Specification</u>" as RestrictedAccess #00ff00

        object "<u>IEEE_TPS : Journal</u>" as IEEE_TPS #00ff00 {
            title = "IEEE Transactions on Plasma Science"@en ^^ Multilingual_String
            issn = "1939-9375" ^^ ISSN
        }

        object "<u>10.1109/TPS.1987.4316723 : Journal Article</u>" as Article101109 #00ff00 {
                DOI = "10.1109/TPS.1987.4316723" ^^ DOI_Type
                title = "Bulk and surface plasmons in
                \t artificially structured materials"@en
                publicationDate = 1987 ^^ Date
                startPage = "394"
                endPage = "410"
                volume = "15"
                number = "4"
        }

        Article101109 o--> IEEE_TPS : source >

        Article101109 o--> RestrictedAccess : accessRights >

    !endsub

    !startsub authorships

         object "<u>Josiah Article101109:Authorship</u>" as JosiahArticle101109 #ffffff {
                 correspondingAuthor = "false" ^^ Boolean
         }

         object "<u>Affiliation Josiah Article101109 : Affiliation_Statement</u>" as AffiliationJosiahArticle101109 #ffffff {
                 displayAffiliation = "Brown University of Providence, Providence, RI, USA" ^^ String
                 displayPersonName = "Josiah S. Carberry" ^^ String
         }

         JosiahArticle101109 o--> AffiliationJosiahArticle101109 : affiliation >

         JosiahBrownUniversity o--> AffiliationJosiahArticle101109 : is the foundation for >

         JosiahArticle101109 o--> Josiah : actor >

         JosiahArticle101109 o--> Article101109 : document >

         object "<u>John Article101109:Authorship</u>" as JohnArticle101109 #ffffff {
                  correspondingAuthor = "true" ^^ Boolean
         }

         object "<u>Affiliation John Article101109 : Affiliation_Statement</u>" as AffiliationJohnArticle101109 #ffffff {
                  displayAffiliation = "Brown University of Providence, Providence, RI, USA" ^^ String
                  displayPersonName = "John J. Quinn" ^^ String
         }

         JohnArticle101109 o--> AffiliationJohnArticle101109 : affiliation >

         JohnArticle101109 o--> Article101109 : document >


    !endsub

@enduml