@startuml


    !startsub persons

        object "<u>Josiah:Person</u>" as Josiah #ffffff {
           personName = {
           \t firstNames = "Josiah"@en ^^ Multilingual_String
           \t familyNames = "Carberry"@en ^^ Multilingual_String
           } ^^ PersonName
           description = "Josiah Stinkney Carberry is a fictional professor,
           \t created as a joke in 1929. He is said to still teach at Brown University,
           \t and to be known for his work in "psychoceramics", the supposed study of
           \t "cracked pots". See his Wikipedia entry for more details."@en ^^ Multilingual_String
           keywords = ["psychoceramics"@en "ionian philology"@en] List<Multilingual_String>
           orcid_id = "https://orcid.org/0000-0002-1825-0097" ^^ ORCID_iD
           scopus_author_id = "7007156898" ^^ SCOPUS_Author_ID
           websiteURL = "http://library.brown.edu/about/hay/carberry.php"
           otherIDs = [
           \t\t\t {
           \t\t\t\t label = "Wikipedia Entry"@en ^^ Multilingual_String
           \t\t\t\t value = "http://en.wikipedia.org/wiki/Josiah_Carberry" ^^ String
           \t\t\t}
           \t\t] ^^ List<ID>
        }

    !endsub

    !startsub institutions

        object "<u>Wesleyan University:Organisation_Unit</u>" as WesleyeanUniversity #ffffff {
                name = "Wesleyan University"@en ^^ Multilingual_String
                rorId = "https://ror.org/05h7xva58" ^^ ROR_ID
                websiteURL = "https://www.wesleyan.edu/" ^^ URI
                address = {
                \tcity = "Midletown"@en ^^ Multilingual_String
                \tstateOrProvince = "Connecticut"@en ^^ Multilingual_String
                \tcountry = "USA"@en ^^ Multilingual_String
                } ^^ Postal_Address
            }

        object "<u>Brown University:Organisation_Unit</u>" as BrownUniversity #ffffff {
                name = "Brown University"@en ^^ Multilingual_String
                rorId = "https://ror.org/05gq02987" ^^ ROR_ID_Type
                websiteURL = "https://www.brown.edu/" ^^ URI
                address = {
                \tcity = "Providence"@en ^^ Multilingual_String
                \tstateOrProvince = "Rhode Island"@en ^^ Multilingual_String
                \tcountry = "USA"@en ^^ Multilingual_String
                } ^^ Postal_Address
            }

    !endsub

    !startsub employments

        object "<u>Josiah Wesleyan University:Employment</u>" as JosiahWesleyeanUniversity #ffffff {
                dateRange = {
                \t startDate = "1930-02-29" ^^ Date
                \t startDateInclusive = "true" ^^ Boolean
                } ^^ Date_Range
                positionTitle = {
                \t title = "Professor"@en ^^ Multilingual_String
                } ^^ Position_Title
            }

        object "<u>Josiah Brown University:Employment</u>" as JosiahBrownUniversity #ffffff {
                dateRange = {
                \t startDate = "1929-02-29" ^^ Date
                \t startDateInclusive = "true" ^^ Boolean
                } ^^ Date_Range
                positionTitle = {
                \t title = "Professor"@en ^^ Date
                } ^^ Position_Title
            }

        JosiahWesleyeanUniversity o--> Josiah : actor >

        JosiahBrownUniversity o--> Josiah : actor >

        JosiahWesleyeanUniversity o--> WesleyeanUniversity : involved in >

        JosiahBrownUniversity o--> BrownUniversity : involved in >

    !endsub

    !startsub articles

        object "<u>Restricted Access: Restricted Access COAR v.1.0 Accessibility Specification</u>" as RestrictedAccess #00ff00

        object "<u>IEEE_TPS : Journal</u>" as IEEE_TPS #00ff00 {
            title = "IEEE Transactions on Plasma Science"@en ^^ Multilingual_String
            issn = "1939-9375" ^^ ISSN
        }

        object "<u>10.1109/TPS.1987.4316723 : Journal Article</u>" as Article101109 #00ff00 {
                DOI = "10.1109/TPS.1987.4316723" ^^ DOI_Type
                title = "Bulk and surface plasmons in
                \t artificially structured materials"@en ^^ Multilingual_String
                publicationDate = 1987 ^^ Date
                startPage = "394"
                endPage = "410"
                volume = "15"
                number = "4"
        }

        Article101109 o--> IEEE_TPS : source >

        Article101109 o--> RestrictedAccess : accessRights >

    !endsub

    !startsub authorships

         object "<u>Josiah Article101109:Authorship</u>" as JosiahArticle101109 #ffffff {
                 correspondingAuthor = "false" ^^ Boolean
         }

         object "<u>Affiliation Josiah : Affiliation_Statement</u>" as AffiliationJosiah #ffffff {
                 displayAffiliation = "Brown University of Providence, Providence, RI, USA" ^^ String
                 displayPersonName = "Josiah S. Carberry" ^^ String
         }

         JosiahArticle101109 o--> AffiliationJosiah : affiliation >

         JosiahBrownUniversity o--> AffiliationJosiah : is the foundation for >

         JosiahArticle101109 o--> Josiah : actor >

         JosiahArticle101109 o--> Article101109 : document >

         object "<u>John Article101109:Authorship</u>" as JohnArticle101109 #ffffff {
                  correspondingAuthor = "true" ^^ Boolean
         }

         object "<u>Affiliation John Article101109 : Affiliation_Statement</u>" as AffiliationJohnArticle101109 #ffffff {
                  displayAffiliation = "Brown University of Providence, Providence, RI, USA" ^^ String
                  displayPersonName = "John J. Quinn" ^^ String
         }

         JohnArticle101109 o--> AffiliationJohnArticle101109 : affiliation >

         JohnArticle101109 o--> Article101109 : document >


    !endsub

    !startsub project

        object "<u>INSP:Project</u>" as INSP #ffffff {
                 name = "Investigation of novel surface plasmons"@en ^^ Multilingual_String
                 acronym = "INSP" ^^ String
                 dateRange = {
                  \t startDate = "1985-02-29" ^^ Date
                  \t startDateInclusive = "true" ^^ Boolean
                  \t endDate = "1989-02-29" ^^ Date
                  \t endDateInclusive = "true" ^^ Boolean
                  } ^^ Date_Range
        }

        object "<u>INSP_WP1:Project</u>" as INSP_WP1 #ffffff {
                 name = "Artificially structured materials"@en ^^ Multilingual_String
                 acronym = "WP1" ^^ String
        }

        INSP_WP1 o--> INSP : part of >

        object "<u>NIH_1049:Funding</u>" as NIH_1049 #ffffff {
                 grantID = 1049 ^^ Grant_ID
                 budget = {
                 \t amount = 1000000 ^^ Decimal
                 \t currencyCode = "USD" ^^ ISO_4217_Alpha_Code
                 } ^^ Monetary_Ammount
        }

        INSP o--> NIH_1049 : funding source >

    !endsub

    !startsub contributionStatementToArticle

        object "<u>JosiahContributionStatement:CRediTContributionStatement</u>" as JosiahContributionStatement #00ff00 {
                 roleType = Writing - original draft ^^ CRediT_Role_Type
                 degreeOfContribution = Lead ^^ CRediT_Degree_of_Contribution
        }

        object "<u>JosiahResourceUsageStatement:ResourceUsageStatement</u>" as JosiahResourceUsageStatement #ffffff {
                 statement = "This work was supported by the NIH [grant number 1049]."@en ^^ Multilingual_String
        }

        JosiahContributionStatement o--> JosiahResourceUsageStatement : resource usage statement >

        JosiahResourceUsageStatement o--> NIH_1049 : funding >

        JosiahArticle101109 o--> JosiahContributionStatement : contribution statement >

    !endsub

    !startsub contributionToProject

        object "<u>JosiahContributionToProject:ContributionToProject</u>" as JosiahContributionToProject #ffffff {
                 dateRange = {
                   \t startDate = "1985-02-29" ^^ Date
                   \t startDateInclusive = "true" ^^ Boolean
                   \t endDate = "1989-02-29" ^^ Date
                   \t endDateInclusive = "true" ^^ Boolean
                 } ^^ Date_Range
        }

        JosiahContributionToProject o--> AffiliationJosiah : affiliation statement >

        JosiahContributionToProject o--> Josiah : of >

        JosiahContributionToProject o--> INSP : to >

        object "<u>JosiahContributionToWP:ContributionToProject</u>" as JosiahContributionToWP #ffffff {
                 dateRange = {
                   \t startDate = "1986-02-29" ^^ Date
                   \t startDateInclusive = "true" ^^ Boolean
                   \t endDate = "1988-02-29" ^^ Date
                   \t endDateInclusive = "true" ^^ Boolean
                 } ^^ Date_Range
        }

        JosiahContributionToWP o--> AffiliationJosiah : affiliation statement >

        JosiahContributionToWP o--> Josiah : of >

        JosiahContributionToWP o--> INSP_WP1 : to >

    !endsub

    !startsub contributionStatementToProject

        object "<u>JosiahContributionStatementToProject:ContributionStatement</u>" as JosiahContributionStatementToProject #ffffff {
                 statement = "Participate in the project as a researcher"@en ^^ Multilingual_String
        }

        object "<u>JosiahContributionStatementToWP1:ContributionStatement</u>" as JosiahContributionStatementToWP1 #ffffff {
                 statement = "Lead the WP1"@en ^^ Multilingual_String
        }

        JosiahContributionStatementToProject o--> JosiahResourceUsageStatement : resource usage statement >

        JosiahContributionStatementToWP1 o--> JosiahResourceUsageStatement : resource usage statement >

        JosiahContributionToProject o--> JosiahContributionStatementToProject : contribution statement >

        JosiahContributionToWP o--> JosiahContributionStatementToWP1 : contribution statement >

    !endsub

    !startsub reviewingActivity

        object "<u>JosiahContributionToJournal:ContributionToJournal</u>" as JosiahContributionToJournal #ffffff {
                 dateRange = {
                   \t startDate = "2004-02-02" ^^ Date
                   \t startDateInclusive = "true" ^^ Boolean
                   \t endDate = "2004-12-31" ^^ Date
                   \t endDateInclusive = "true" ^^ Boolean
                 } ^^ Date_Range
        }

        object "<u>JoP : Journal</u>" as JoP #00ff00 {
            title = "The  of Psychoceramics"@en ^^ Multilingual_String
            issn = "1234-5678" ^^ ISSN
        }

        JosiahContributionToJournal o--> AffiliationJosiah : affiliation statement >

        JosiahContributionToJournal o--> Josiah : of >

        JosiahContributionToJournal o--> JoP : to >

        object "<u>JosiahContributionStatementToJournal:ContributionStatement</u>" as JosiahContributionStatementToJournal #ffffff {
                 statement = "Performed review of one article for this journal"@en ^^ Multilingual_String
        }

        JosiahContributionToJournal o--> JosiahContributionStatementToJournal : contribution statement >

    !endsub

@enduml